-- Import 358 customers as approved (completed)
INSERT INTO customers (company_name, customer_type, stage, extra_data, signatures) VALUES
('4A Yarn Dyeing Ltd.','Regular','completed','{}','{}'),
('A PLUS GROUP','Regular','completed','{}','{}'),
('A-ONE POLAR LTD','Regular','completed','{}','{}'),
('A.M INTERNATIONAL','Regular','completed','{}','{}'),
('AB APPARELS LTD.','Regular','completed','{}','{}'),
('ACS Textile (BD) Limited','Regular','completed','{}','{}'),
('ACS Towel Ltd.','Regular','completed','{}','{}'),
('ADARSHA ACCESSORIES','Regular','completed','{}','{}'),
('AHMED FASHIONS','Regular','completed','{}','{}'),
('AHSIAR FASHION LTD.','Regular','completed','{}','{}'),
('AJ FASHIONS LTD.','Regular','completed','{}','{}'),
('ALIZA FASHION LTD.','Regular','completed','{}','{}'),
('ALPHA CLOTHING LTD','Regular','completed','{}','{}'),
('AMI CHEMICALS','Regular','completed','{}','{}'),
('ANZIR APPARELS LTD.','Regular','completed','{}','{}'),
('ARRAY FASHION','Regular','completed','{}','{}'),
('ATASHI FASHION LTD','Regular','completed','{}','{}'),
('Abir Fashions','Regular','completed','{}','{}'),
('Absolute Quility Wear Ltd.','Regular','completed','{}','{}'),
('Ace Apparels Ltd.','Regular','completed','{}','{}'),
('Achieve Fashion Ltd.','Regular','completed','{}','{}'),
('Adnan Traders','Regular','completed','{}','{}'),
('Advanced Composite Textile Limited','Regular','completed','{}','{}'),
('Ahsan Habib','Regular','completed','{}','{}'),
('Ahshan Habib Asst. Manager, ERP-9567','Regular','completed','{}','{}'),
('Al- Modina Trade','Regular','completed','{}','{}'),
('Al-Modina','Regular','completed','{}','{}'),
('Alam Traders','Regular','completed','{}','{}'),
('Allahar Daan (1611)','Regular','completed','{}','{}'),
('Alliance Knit composite Ltd.','Regular','completed','{}','{}'),
('Ama Syntex Ltd.','Regular','completed','{}','{}'),
('Aman Tex Ltd.','Regular','completed','{}','{}'),
('Anupam Hosiery Ind. Pvt. Ltd.','Regular','completed','{}','{}'),
('Anwar Morshed Manager-Sales & Marketing , ERP-12906','Regular','completed','{}','{}'),
('Anzir Terry Towel Mills Ltd.','Regular','completed','{}','{}'),
('Artex Fabrics Limited','Regular','completed','{}','{}'),
('Artex Knit Limited','Regular','completed','{}','{}'),
('Auko Tex Ltd.','Regular','completed','{}','{}'),
('Ayesha & galeya fahion Ltd.','Regular','completed','{}','{}'),
('Aysah Trading','Regular','completed','{}','{}'),
('BETTEX INDUSTRIES LTD.','Regular','completed','{}','{}'),
('BHML Industries ltd','Regular','completed','{}','{}'),
('Baraka fashions Ltd.','Regular','completed','{}','{}'),
('Best Wool Sweaters Ltd.','Regular','completed','{}','{}'),
('Bettex HK Ltd','Regular','completed','{}','{}'),
('Bilkis Enterprise (Wastage)','Regular','completed','{}','{}'),
('Bingsum Textile Mills Ltd.','Regular','completed','{}','{}'),
('Bismillah Enterprise-Wastage','Regular','completed','{}','{}'),
('Bismillah Material Accessories','Regular','completed','{}','{}'),
('Bliss Fashions & Crafts Ltd.','Regular','completed','{}','{}'),
('Body Fashion (Pvt.) Ltd.','Regular','completed','{}','{}'),
('Brothers Fashion Ltd.','Regular','completed','{}','{}'),
('C.B.M. International Ltd.','Regular','completed','{}','{}'),
('CENTEX TEXTILE & APPARELS LTD.','Regular','completed','{}','{}'),
('CLAMOON GARMENTS LTD','Regular','completed','{}','{}'),
('COLUMBIA APPARELS LTD','Regular','completed','{}','{}'),
('CRONY TEX SWEATER LIMITED.','Regular','completed','{}','{}'),
('CROSSLINE KNIT FABRICS LTD','Regular','completed','{}','{}'),
('CROSSLINE WOVEN APPARELS LTD.','Regular','completed','{}','{}'),
('Chaity Composite Ltd.','Regular','completed','{}','{}'),
('Chorka Textile Ltd.','Regular','completed','{}','{}'),
('Classic Fashion Concept Ltd.','Regular','completed','{}','{}'),
('Classical Handmade Products BD Ltd','Regular','completed','{}','{}'),
('Coast To Coast (Pvt) Ltd.','Regular','completed','{}','{}'),
('Colotex Apparels Ltd.','Regular','completed','{}','{}'),
('Columbia Garments Ltd.','Regular','completed','{}','{}'),
('Comptex Bangladesh Ltd.','Regular','completed','{}','{}'),
('Crossline Factory (PVT) Ltd','Regular','completed','{}','{}'),
('Crown Wears (PVT) Limited','Regular','completed','{}','{}'),
('DAEYU BANGLADESH LTD.','Regular','completed','{}','{}'),
('DEBONAIR BAG & LUGGAGE LTD.','Regular','completed','{}','{}'),
('DESIGNER FASHION LTD.','Regular','completed','{}','{}'),
('DHAKA SOCKS LTD.','Regular','completed','{}','{}'),
('DIPS APPAREL LTD.','Regular','completed','{}','{}'),
('DOREEN GARMENTS LTD','Regular','completed','{}','{}'),
('Debonair Padding & Quilting Solution Limited','Regular','completed','{}','{}'),
('Denimach Ltd.','Regular','completed','{}','{}'),
('Designtex Knitwear Ltd.','Regular','completed','{}','{}'),
('Dew Fashion Ltd','Regular','completed','{}','{}'),
('Dird Composite Textile Ltd.','Regular','completed','{}','{}'),
('Dress & Dismatic (Pvt) Limited','Regular','completed','{}','{}'),
('Drop & Dross Sourcing Ltd.','Regular','completed','{}','{}'),
('Durable Plastics Ltd.','Regular','completed','{}','{}'),
('E H FABRICS LTD.','Regular','completed','{}','{}'),
('ELEGANCE ORIENTALE LTD.','Regular','completed','{}','{}'),
('EURO OSMAN STAR LIFE','Regular','completed','{}','{}'),
('EVERBRIGHT SWEATERS LTD.','Regular','completed','{}','{}'),
('Echoknits Ltd.','Regular','completed','{}','{}'),
('Emon Fashion Ltd.','Regular','completed','{}','{}'),
('Energypac Fashions Ltd.','Regular','completed','{}','{}'),
('Esquire Knit Composite Ltd','Regular','completed','{}','{}'),
('Euro Denim & Fashion Ltd','Regular','completed','{}','{}'),
('Ever Fashion Tongi Ltd.','Regular','completed','{}','{}'),
('Evitex Dress Shirt Ltd.','Regular','completed','{}','{}'),
('F B FOOTWEAR LTD.','Regular','completed','{}','{}'),
('F.B. Fashion (Pvt.) Ltd.','Regular','completed','{}','{}'),
('FASHION FLOW APPARELS LTD.','Regular','completed','{}','{}'),
('FASHION KNIT GARMENTS LTD.','Regular','completed','{}','{}'),
('FASHIONS TRADE INDUSTRIES','Regular','completed','{}','{}'),
('FNF Trade International','Regular','completed','{}','{}'),
('FULLCHARM FASHION KNITTERS LTD.','Regular','completed','{}','{}'),
('Fahad Enterprise (Wastage)','Regular','completed','{}','{}'),
('Faiza Industries Ltd.','Regular','completed','{}','{}'),
('Fajr Advertising','Regular','completed','{}','{}'),
('Fakhruddin Textile Mills Ltd. (Urmi Group)','Regular','completed','{}','{}'),
('Fakir Knitwears Ltd.','Regular','completed','{}','{}'),
('Fariha Knit Tex Ltd.','Regular','completed','{}','{}'),
('Fashion Asia Ltd.','Regular','completed','{}','{}'),
('Fashion Makers Ltd.','Regular','completed','{}','{}'),
('Fashion.Com','Regular','completed','{}','{}'),
('Fortis Garments Ltd.','Regular','completed','{}','{}'),
('GERARD FRES LIMITED','Regular','completed','{}','{}'),
('GOODEARTH APPARELS LIMITED.','Regular','completed','{}','{}'),
('Giant Textile Ltd.','Regular','completed','{}','{}'),
('Global Fashion Garments Ltd.','Regular','completed','{}','{}'),
('Glory Textile & Apparels Limited','Regular','completed','{}','{}'),
('Grameen Fabrics & Fashions Ltd.','Regular','completed','{}','{}'),
('Gramtech Knit Dyeing Finishing & Garments Industries Ltd.','Regular','completed','{}','{}'),
('HANDZ CLOTHING BD LIMITED','Regular','completed','{}','{}'),
('HOSSAIN DYEING & PRINTING MILLS LTD. (UNIT-2)','Regular','completed','{}','{}'),
('HRB APPARELS LTD.','Regular','completed','{}','{}'),
('Habitus Fashion Ltd (2083)','Regular','completed','{}','{}'),
('Hams Garments Ltd.','Regular','completed','{}','{}'),
('Hana Fabrics','Regular','completed','{}','{}'),
('Harkom Setabganj Ltd.','Regular','completed','{}','{}'),
('Hasan Enterprise (Abul)','Regular','completed','{}','{}'),
('Hi-Tech Performance Apprels Ltd.','Regular','completed','{}','{}'),
('Hornbill Apparel Limited','Regular','completed','{}','{}'),
('INTERLOOP BD LIMITED','Regular','completed','{}','{}'),
('IRIS DESIGN LTD.','Regular','completed','{}','{}'),
('Icarus Fashion Ltd.','Regular','completed','{}','{}'),
('Inactive Echoknits Ltd.','Regular','completed','{}','{}'),
('Inactive Gramtech Knit Dyeing Finishing & Garments Industries Ltd.','Regular','completed','{}','{}'),
('Innovative Knitex Ltd.','Regular','completed','{}','{}'),
('Intensity Ltd.','Regular','completed','{}','{}'),
('International Classic Composite Ltd.','Regular','completed','{}','{}'),
('Interstoff Apparel Ltd','Regular','completed','{}','{}'),
('Intimate Attire Ltd.','Regular','completed','{}','{}'),
('Ishwardi Matsuoka Bangladesh Ltd. (IMBD)','Regular','completed','{}','{}'),
('Ismail Anzuman Ara Fabrics Limited','Regular','completed','{}','{}'),
('Ismail Spinning Mills Limited','Regular','completed','{}','{}'),
('Ismail Spinning Mills Limited (Saad Group)','Regular','completed','{}','{}'),
('Ismail Textile Mills Limited','Regular','completed','{}','{}'),
('J.L Sweater Ltd.','Regular','completed','{}','{}'),
('JS Cotton International','Regular','completed','{}','{}'),
('Jamou Impotrade','Regular','completed','{}','{}'),
('Jams Sweaters (PVT.) Ltd','Regular','completed','{}','{}'),
('Jamuna Apparels Limited.','Regular','completed','{}','{}'),
('Jann Composite Mills Ltd.','Regular','completed','{}','{}'),
('Jeans Manufacturing Co. Ltd.','Regular','completed','{}','{}'),
('Jewel Rana Manager-Sales & Marketing , ERP-','Regular','completed','{}','{}'),
('Jihan Fabrics (5122)','Regular','completed','{}','{}'),
('Joy Auto Garments Ltd','Regular','completed','{}','{}'),
('K-TEX INDUSTRIAL CO. LTD.','Regular','completed','{}','{}'),
('K.A. Design Ltd.','Regular','completed','{}','{}'),
('KAPTEX SWEATER LTD.','Regular','completed','{}','{}'),
('KIMS CORPORATION LTD.','Regular','completed','{}','{}'),
('KNIT ASIA LIMITED','Regular','completed','{}','{}'),
('Kamal Enterprise','Regular','completed','{}','{}'),
('Kaniz Garments Limited','Regular','completed','{}','{}'),
('Karim Textiles Ltd.','Regular','completed','{}','{}'),
('Karupannya Rangpur Ltd.','Regular','completed','{}','{}'),
('Katex Fashion Clothing Ltd.','Regular','completed','{}','{}'),
('Knit Horizon Ltd.','Regular','completed','{}','{}'),
('Liberty Knitwear Ltd.','Regular','completed','{}','{}'),
('Lida Textile & Dyeing','Regular','completed','{}','{}'),
('Life Textile (Pvt) Limited','Regular','completed','{}','{}'),
('Liz Fashion Industry Limited','Regular','completed','{}','{}'),
('Lucky Star Apparel''s Limited','Regular','completed','{}','{}'),
('Luminous Textile Ltd.','Regular','completed','{}','{}'),
('Lyric Industries (Pvt.) Ltd.','Regular','completed','{}','{}'),
('M&M Travelling Goods (BD) Ltd.','Regular','completed','{}','{}'),
('M.S. DYEING,PRINTING & FINISHING LTD','Regular','completed','{}','{}'),
('M.T. SWEATERS LTD.','Regular','completed','{}','{}'),
('MARS STITCH LTD.','Regular','completed','{}','{}'),
('MASIHATA SWEATERS LTD.','Regular','completed','{}','{}'),
('MAVIS GARMENTS LTD','Regular','completed','{}','{}'),
('MD. Jewel Rana','Regular','completed','{}','{}'),
('MD. Mahfuzur Rahman','Regular','completed','{}','{}'),
('MEEK SWEATER LTD.','Regular','completed','{}','{}'),
('MEGA FASHIONWEAR LTD.','Regular','completed','{}','{}'),
('MN TEX BD','Regular','completed','{}','{}'),
('MUAZUDDIN KNIT FASHION LTD.','Regular','completed','{}','{}'),
('MULTIFABS LIMITED.','Regular','completed','{}','{}'),
('Maa Enterprise-Shofiqul Islam','Regular','completed','{}','{}'),
('Mahadi Fashion (Pvt.) Limited','Regular','completed','{}','{}'),
('Mahmud Fashion Limited','Regular','completed','{}','{}'),
('Mahmud Jeans Ltd.','Regular','completed','{}','{}'),
('Majumder Garments Ltd.','Regular','completed','{}','{}'),
('Marium Textile Mills Limited','Regular','completed','{}','{}'),
('Md. Alamgir Hossain Asst.Manager, 8829','Regular','completed','{}','{}'),
('Md. Mahfuzur Rahman Assistant Manager, ERP-12798','Regular','completed','{}','{}'),
('Md.Asaduzzaman Accessories Sales & Marketing Specialist, ERP-12890','Regular','completed','{}','{}'),
('Md.Mamun khan Asst. Manager, ERP-2619','Regular','completed','{}','{}'),
('Mimo Cotton Zone Ltd.','Regular','completed','{}','{}'),
('Mk Apparels Ltd.','Regular','completed','{}','{}'),
('Modele De Capital Ind. Ltd.','Regular','completed','{}','{}'),
('Mometex Expo Ltd.','Regular','completed','{}','{}'),
('Mouchak Knit Composite Limited','Regular','completed','{}','{}'),
('Mr. Hafizur Rahman-GM (Tax)','Regular','completed','{}','{}'),
('Muhtadir AL Munif','Regular','completed','{}','{}'),
('Murad Apparels Ltd.','Regular','completed','{}','{}'),
('N-A Sourching','Regular','completed','{}','{}'),
('N.A.Z  Bangladesh Ltd.','Regular','completed','{}','{}'),
('NATURAL INDIGO LTD','Regular','completed','{}','{}'),
('NEEDLE APPARELS LTD','Regular','completed','{}','{}'),
('NIAGARA TEXTILE  LTD.','Regular','completed','{}','{}'),
('NORP KNIT INDUSTRIES LTD.','Regular','completed','{}','{}'),
('NRN KNITTING & GARMENTS LTD','Regular','completed','{}','{}'),
('Nakano International','Regular','completed','{}','{}'),
('Native Packages Ltd.','Regular','completed','{}','{}'),
('Natural Denims Limited','Regular','completed','{}','{}'),
('Natural Sweater Village Ltd.','Regular','completed','{}','{}'),
('New Tex One','Regular','completed','{}','{}'),
('Newage Apparels Ltd.','Regular','completed','{}','{}'),
('Nice Denim Mills Ltd','Regular','completed','{}','{}'),
('Nice Denim Mills Ltd. ( Solid Dyeing Fabrics )','Regular','completed','{}','{}'),
('Nice Denim Mills Ltd.(Saad Group)','Regular','completed','{}','{}'),
('Nice Fabrics Processing Ltd. - 2','Regular','completed','{}','{}'),
('Nice Microfab Limited','Regular','completed','{}','{}'),
('Nice Spinning Mills Ltd.','Regular','completed','{}','{}'),
('Nice Spun Mills Limited','Regular','completed','{}','{}'),
('Nice Synthetic Yarn Mills Ltd.','Regular','completed','{}','{}'),
('Noman Composite Textile Limited','Regular','completed','{}','{}'),
('Noman Fabrics Limited - Unit-1','Regular','completed','{}','{}'),
('Noman Fabrics Limited - Unit-2','Regular','completed','{}','{}'),
('Noman Fashion Fabrics Limited','Regular','completed','{}','{}'),
('Noman Home Textile Mills Limited (Saad Group)','Regular','completed','{}','{}'),
('Noman Spinning Mills Limited','Regular','completed','{}','{}'),
('Noman Terry Towel Mills Limited','Regular','completed','{}','{}'),
('Noman Textile Mills Limited','Regular','completed','{}','{}'),
('Noman Weaving Mills Limited','Regular','completed','{}','{}'),
('Norban Comtex Ltd.','Regular','completed','{}','{}'),
('Nur-E-Habib Traders','Regular','completed','{}','{}'),
('OCEAN SWEATER IND PVT LTD.(UNIT-01)','Regular','completed','{}','{}'),
('ONEDROB LTD','Regular','completed','{}','{}'),
('Oishi Designs Ltd.','Regular','completed','{}','{}'),
('Onima Fabrics','Regular','completed','{}','{}'),
('Orient Allure Knitwear Ltd.','Regular','completed','{}','{}'),
('P.A. Knit Composite Ltd.','Regular','completed','{}','{}'),
('PINAKI GROUP','Regular','completed','{}','{}'),
('PROSTAR APPARELS LTD','Regular','completed','{}','{}'),
('PURBANI GROUP','Regular','completed','{}','{}'),
('PURE COMFORT LTD.','Regular','completed','{}','{}'),
('Pacific Cotton Limited','Regular','completed','{}','{}'),
('Padma Satel Arab Fashions Ltd.','Regular','completed','{}','{}'),
('Palmal Group of Industries','Regular','completed','{}','{}'),
('Parkscene Bangladesh Ltd','Regular','completed','{}','{}'),
('Pioneer Knitwears (BD) Ltd.','Regular','completed','{}','{}'),
('Plummy Fashions Ltd.','Regular','completed','{}','{}'),
('Power Hi Tech Ltd.','Regular','completed','{}','{}'),
('Premier 1888 Ltd.','Regular','completed','{}','{}'),
('Progress Apparels BD Ltd.','Regular','completed','{}','{}'),
('Qarar Global','Regular','completed','{}','{}'),
('R S TRADERS','Regular','completed','{}','{}'),
('RAHAMAT FASHION WEAR LTD','Regular','completed','{}','{}'),
('RAM APPARELS LTD.','Regular','completed','{}','{}'),
('RIPON KNITWEAR LIMITED.','Regular','completed','{}','{}'),
('RK Accessories','Regular','completed','{}','{}'),
('ROSE SWEATER LTD.','Regular','completed','{}','{}'),
('Radiant Sweater Ind. Ltd.','Regular','completed','{}','{}'),
('Ragadi Textile Mills Ltd','Regular','completed','{}','{}'),
('Raidha Collections Ltd.','Regular','completed','{}','{}'),
('Rajib Chowdhury Manager-Sales & Marketing, ERP-8135','Regular','completed','{}','{}'),
('Ratul Knitwears Ltd.','Regular','completed','{}','{}'),
('Reedisha Knitex Limited','Regular','completed','{}','{}'),
('Reedisha Texstripe Limited','Regular','completed','{}','{}'),
('Reedisha Textile Ltd.- Dhaka (2202)','Regular','completed','{}','{}'),
('Rima Transport & Supply Agency','Regular','completed','{}','{}'),
('Roar Fashion Ltd.','Regular','completed','{}','{}'),
('Rose Intimates Ltd.','Regular','completed','{}','{}'),
('Rowa Fashion Ltd','Regular','completed','{}','{}'),
('S & S CORPORATION','Regular','completed','{}','{}'),
('S.A ENTERPRICE  LTD.','Regular','completed','{}','{}'),
('S.S. SWEATER LTD.','Regular','completed','{}','{}'),
('SHARMIN GROUP','Regular','completed','{}','{}'),
('SHINEST APPARELS LTD.','Regular','completed','{}','{}'),
('SIMBA FASHIONS LIMITED','Regular','completed','{}','{}'),
('SINHA KNIT INDUSTRIES LTD.','Regular','completed','{}','{}'),
('SINHA Knit and Denims Limited.','Regular','completed','{}','{}'),
('SM KNITWEARS LTD.','Regular','completed','{}','{}'),
('STARLING CREATION LTD.','Regular','completed','{}','{}'),
('SUNRISE KNITWEARS LTD.','Regular','completed','{}','{}'),
('SYNAMATIC''S FASHION OUTFIT LTD.','Regular','completed','{}','{}'),
('Saad Group','Regular','completed','{}','{}'),
('Saad Saan Apparels Ltd.','Regular','completed','{}','{}'),
('Saad Saan Textile Mills Limited','Regular','completed','{}','{}'),
('Saad Textile Processing Ltd. (Saad Group)','Regular','completed','{}','{}'),
('Saan Composite Textile Ltd. (Saad Group)','Regular','completed','{}','{}'),
('Saan Textile Mills Ltd. (Saad Group)','Regular','completed','{}','{}'),
('Sadat Apparels Ltd','Regular','completed','{}','{}'),
('Sakib Rezowan, (Erp-12909)','Regular','completed','{}','{}'),
('Sams Attire Ltd.','Regular','completed','{}','{}'),
('Self Innovative Fashion Ltd','Regular','completed','{}','{}'),
('Seven Star Garments Ltd.','Regular','completed','{}','{}'),
('Shahjalal Islami Bank Ltd.','Regular','completed','{}','{}'),
('Shamsunnahar Enterprise','Regular','completed','{}','{}'),
('Shanta Expression Ltd.','Regular','completed','{}','{}'),
('Sharaf Apparels Limited','Regular','completed','{}','{}'),
('Shovon Group of Companies Ltd.','Regular','completed','{}','{}'),
('Sicily Garments Ltd.','Regular','completed','{}','{}'),
('Snowtex Outerwear Ltd.','Regular','completed','{}','{}'),
('Southend Sweater Co. Ltd.','Regular','completed','{}','{}'),
('Square Apparels Ltd.','Regular','completed','{}','{}'),
('Square Denims Limited.','Regular','completed','{}','{}'),
('Square Fashions Limited.','Regular','completed','{}','{}'),
('Stark Bag Industries Ltd.','Regular','completed','{}','{}'),
('Sterling Denims Ltd.','Regular','completed','{}','{}'),
('Sufia Collection. (2462)','Regular','completed','{}','{}'),
('Sufia Cotton Mills Limited-(Spinning) (Saad Group)','Regular','completed','{}','{}'),
('Sufia Cotton Mills Ltd.(weaving) (Saad Group)','Regular','completed','{}','{}'),
('Sufia Fabrics Limited','Regular','completed','{}','{}'),
('Supreme Smart Wear Ltd.','Regular','completed','{}','{}'),
('TAMISHNA FASHION WEAR LTD.','Regular','completed','{}','{}'),
('TEX ZIPPERS (BD) LIMITED','Regular','completed','{}','{}'),
('TIME & QUALITY EXPRESS LTD.','Regular','completed','{}','{}'),
('TNZ Apparels Ltd.','Regular','completed','{}','{}'),
('TOPAZ DRESSES LTD','Regular','completed','{}','{}'),
('TORQUE FASHION LTD.','Regular','completed','{}','{}'),
('TORY FASHION WEAR LTD.','Regular','completed','{}','{}'),
('TRZ GARMENTS INDUSTRY LTD.','Regular','completed','{}','{}'),
('TSR APPARELS LTD.','Regular','completed','{}','{}'),
('Talha Fabrics Limited','Regular','completed','{}','{}'),
('Talha Spinning Mills Limited','Regular','completed','{}','{}'),
('Talha Texpro Limited','Regular','completed','{}','{}'),
('Tamam Trims BD Ltd.','Regular','completed','{}','{}'),
('Tanvir Hassan Jewel AGM -Sales & Marketing, ERP-7066','Regular','completed','{}','{}'),
('Tarasima Apparels Limited','Regular','completed','{}','{}'),
('Taslima Textile (2490)','Regular','completed','{}','{}'),
('Temakaw Fashion Ltd.','Regular','completed','{}','{}'),
('Texeurop (BD) Ltd.','Regular','completed','{}','{}'),
('Tigerco Limited','Regular','completed','{}','{}'),
('Torque Design Ltd.','Regular','completed','{}','{}'),
('Trims Field Ltd.','Regular','completed','{}','{}'),
('UTTARA KNITWEARS LTD.','Regular','completed','{}','{}'),
('Ultimate Fashions Ltd.','Regular','completed','{}','{}'),
('Unicorn Sweater Ltd.','Regular','completed','{}','{}'),
('United Surgical Ltd.','Regular','completed','{}','{}'),
('Versatile Textiles Ltd.','Regular','completed','{}','{}'),
('Virtual Bottoms Ltd.','Regular','completed','{}','{}'),
('Viyellatex Ltd.','Regular','completed','{}','{}'),
('W Apparels Ltd.','Regular','completed','{}','{}'),
('WRAPS CLOTHES-LINE LTD','Regular','completed','{}','{}'),
('Waleed & Brothers','Regular','completed','{}','{}'),
('Waltz Fashions Ltd.','Regular','completed','{}','{}'),
('YCL International Industries Ltd.','Regular','completed','{}','{}'),
('YUANSHUN ENTERPRISE CO. LTD.','Regular','completed','{}','{}'),
('Yasmin Spinning Mills Limited','Regular','completed','{}','{}'),
('Yasmin Textile Mills Ltd.(Saad Group)','Regular','completed','{}','{}'),
('Z & Z Intimates Ltd.','Regular','completed','{}','{}'),
('ZON RON SWEATERS LTD.','Regular','completed','{}','{}'),
('Zaber & Zubair Fabrics Limited - Fashion','Regular','completed','{}','{}'),
('Zaber & Zubair Fabrics Ltd. - Home','Regular','completed','{}','{}'),
('Zaber Spinning Mills Limited','Regular','completed','{}','{}'),
('Zakaria Enterprise','Regular','completed','{}','{}'),
('Zarba Textile Mills Limited','Regular','completed','{}','{}'),
('Zithi Enterprise','Regular','completed','{}','{}'),
('Zubair Spinning Mills Limited','Regular','completed','{}','{}')
ON DUPLICATE KEY UPDATE stage=VALUES(stage);
